[package]
name = "owl"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
phf = { version = "0.11", features = ["macros"] }
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.0"
